// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropertyManagement.Infrastructure.Data;

#nullable disable

namespace PropertyManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510051959_AddPartnerAndLeadCommission")]
    partial class AddPartnerAndLeadCommission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.BuyerClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BuyerClients");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.CommercialListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdNumber")
                        .HasColumnType("text")
                        .HasColumnName("ad_number");

                    b.Property<string>("AvailableUnits")
                        .HasColumnType("text")
                        .HasColumnName("available_units");

                    b.Property<string>("Broker")
                        .HasColumnType("text")
                        .HasColumnName("broker");

                    b.Property<string>("BrokerageContract")
                        .HasColumnType("text")
                        .HasColumnName("brokerage_contract");

                    b.Property<string>("BuildingAge")
                        .HasColumnType("text")
                        .HasColumnName("building_age");

                    b.Property<string>("ContactDate")
                        .HasColumnType("text")
                        .HasColumnName("contact_date");

                    b.Property<string>("ContractExpiry")
                        .HasColumnType("text")
                        .HasColumnName("contract_expiry");

                    b.Property<string>("Coordinates")
                        .HasColumnType("text")
                        .HasColumnName("coordinates");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeedNumber")
                        .HasColumnType("text")
                        .HasColumnName("deed_number");

                    b.Property<string>("Employee")
                        .HasColumnType("text")
                        .HasColumnName("employee");

                    b.Property<string>("HasElevator")
                        .HasColumnType("text")
                        .HasColumnName("has_elevator");

                    b.Property<string>("HasKey")
                        .HasColumnType("text")
                        .HasColumnName("has_key");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text")
                        .HasColumnName("license_number");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Mobile1")
                        .HasColumnType("text")
                        .HasColumnName("mobile1");

                    b.Property<string>("Mobile2")
                        .HasColumnType("text")
                        .HasColumnName("mobile2");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("text")
                        .HasColumnName("other_details");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text")
                        .HasColumnName("payment_type");

                    b.Property<string>("PropertyStatus")
                        .HasColumnType("text")
                        .HasColumnName("property_status");

                    b.Property<string>("PropertyType")
                        .HasColumnType("text")
                        .HasColumnName("property_type");

                    b.Property<string>("PublishedAqar")
                        .HasColumnType("text")
                        .HasColumnName("published_aqar");

                    b.Property<string>("PublishedBayut")
                        .HasColumnType("text")
                        .HasColumnName("published_bayut");

                    b.Property<string>("PublishedBoard")
                        .HasColumnType("text")
                        .HasColumnName("published_board");

                    b.Property<string>("PublishedDeal")
                        .HasColumnType("text")
                        .HasColumnName("published_deal");

                    b.Property<string>("PublishedDesigns")
                        .HasColumnType("text")
                        .HasColumnName("published_designs");

                    b.Property<string>("PublishedDhaki")
                        .HasColumnType("text")
                        .HasColumnName("published_dhaki");

                    b.Property<string>("PublishedHaraj")
                        .HasColumnType("text")
                        .HasColumnName("published_haraj");

                    b.Property<string>("PublishedInstagram")
                        .HasColumnType("text")
                        .HasColumnName("published_instagram");

                    b.Property<string>("PublishedSnapchat")
                        .HasColumnType("text")
                        .HasColumnName("published_snapchat");

                    b.Property<string>("PublishedTahmid")
                        .HasColumnType("text")
                        .HasColumnName("published_tahmid");

                    b.Property<string>("PublishedTiktok")
                        .HasColumnType("text")
                        .HasColumnName("published_tiktok");

                    b.Property<string>("PublishedTwitter")
                        .HasColumnType("text")
                        .HasColumnName("published_twitter");

                    b.Property<string>("PublishedWhatsapp")
                        .HasColumnType("text")
                        .HasColumnName("published_whatsapp");

                    b.Property<string>("PublishedWhatsappChannel")
                        .HasColumnType("text")
                        .HasColumnName("published_whatsapp_channel");

                    b.Property<string>("PublishedWhatsappGroup")
                        .HasColumnType("text")
                        .HasColumnName("published_whatsapp_group");

                    b.Property<string>("PublishedX")
                        .HasColumnType("text")
                        .HasColumnName("published_x");

                    b.Property<string>("RentAmount")
                        .HasColumnType("text")
                        .HasColumnName("rent_amount");

                    b.Property<string>("RoomsCount")
                        .HasColumnType("text")
                        .HasColumnName("rooms_count");

                    b.Property<string>("RowFlag")
                        .HasColumnType("text")
                        .HasColumnName("row_flag");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("commercial_listings", (string)null);
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeedNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CommissionAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CommissionNotes")
                        .HasColumnType("text");

                    b.Property<string>("CommissionStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastContactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ListedPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerNationalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PreferredContactAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("New");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.LeadImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("LeadId", "SortOrder");

                    b.ToTable("LeadImages");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RentPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.PropertyAmenity", b =>
                {
                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("AmenityId")
                        .HasColumnType("integer");

                    b.HasKey("PropertyId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PropertyAmenities");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsPrimary")
                        .HasFilter("\"IsPrimary\" = true");

                    b.HasIndex("PropertyId");

                    b.HasIndex("PropertyId", "SortOrder");

                    b.ToTable("PropertyImages");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.PropertySale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeedNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("SoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerClientId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertySales");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.RequestRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BedroomCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Employee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MaxBudget")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.ResidentialSeeker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Employee")
                        .HasColumnType("text")
                        .HasColumnName("employee");

                    b.Property<string>("FamilyCount")
                        .HasColumnType("text")
                        .HasColumnName("family_count");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("MaxBudget")
                        .HasColumnType("text")
                        .HasColumnName("max_budget");

                    b.Property<string>("Mobile")
                        .HasColumnType("text")
                        .HasColumnName("mobile");

                    b.Property<string>("Nationality")
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text")
                        .HasColumnName("payment_type");

                    b.Property<string>("PreferredLocation")
                        .HasColumnType("text")
                        .HasColumnName("preferred_location");

                    b.Property<string>("Profession")
                        .HasColumnType("text")
                        .HasColumnName("profession");

                    b.Property<string>("Receiver")
                        .HasColumnType("text")
                        .HasColumnName("receiver");

                    b.Property<string>("RequestDate")
                        .HasColumnType("text")
                        .HasColumnName("request_date");

                    b.Property<string>("RequestDescription")
                        .HasColumnType("text")
                        .HasColumnName("request_description");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("SourceChannel")
                        .HasColumnType("text")
                        .HasColumnName("source_channel");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("residential_seekers", (string)null);
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScreenPermissionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Contract", b =>
                {
                    b.HasOne("PropertyManagement.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyManagement.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Contracts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Lead", b =>
                {
                    b.HasOne("PropertyManagement.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PropertyManagement.Domain.Entities.Partner", "Partner")
                        .WithMany("Leads")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PropertyManagement.Domain.Entities.Property", "Property")
                        .WithMany("Leads")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedToUser");

                    b.Navigation("Partner");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.LeadImage", b =>
                {
                    b.HasOne("PropertyManagement.Domain.Entities.Lead", "Lead")
                        .WithMany("Images")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Owner", b =>
                {
                    b.HasOne("PropertyManagement.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("PropertyManagement.Domain.Entities.Owner", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Partner", b =>
                {
                    b.HasOne("PropertyManagement.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("PropertyManagement.Domain.Entities.Partner", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Payment", b =>
                {
                    b.HasOne("PropertyManagement.Domain.Entities.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Property", b =>
                {
                    b.HasOne("PropertyManagement.Domain.Entities.Owner", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.PropertyAmenity", b =>
                {
                    b.HasOne("PropertyManagement.Domain.Entities.Amenity", "Amenity")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyManagement.Domain.Entities.Property", "Property")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.PropertyImage", b =>
                {
                    b.HasOne("PropertyManagement.Domain.Entities.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.PropertySale", b =>
                {
                    b.HasOne("PropertyManagement.Domain.Entities.BuyerClient", "BuyerClient")
                        .WithMany("Sales")
                        .HasForeignKey("BuyerClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyManagement.Domain.Entities.Property", "Property")
                        .WithMany("Sales")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyerClient");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Tenant", b =>
                {
                    b.HasOne("PropertyManagement.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("PropertyAmenities");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.BuyerClient", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Lead", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Owner", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Partner", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Property", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Leads");

                    b.Navigation("PropertyAmenities");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("PropertyManagement.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
